[package]
name = "micro"
version = "0.1.0"
edition = "2021"
default-run = "micro"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = {path = "../config" }
args = {path = "../args"}